language: python

services:
  - redis-server

python:
  - "2.7"

jdk:
  - oraclejdk7

before_install:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
  - neo4j-community-2.2.0/bin/neo4j-shell -c < database/starwars.cypher

install: "pip install -r requirements.txt"

script: 
  - "celery -A starwars worker --loglevel=info -D"
  - "python manage.py test"
  - "ps auxww | grep 'celery worker' | awk '{print $2}' | xargs kill -9"